on:
  workflow_dispatch:
    inputs:
      target_ruby_version:
          required: false
          default: '238'
        

env:
  TARGET_RUBY_VER: ${{ inputs.target_ruby_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          path: app        

      - uses: actions/checkout@v3
        with:
          repository: 'mpaguilar-merit/dumbops'
          token: ${{ secrets.REPO_KEY }}
          path: build
          
      # Sets up the image tag
      # moves ./app to ./build/app
      # copy ./configs
      - name: Prepare build environment
        run: ./build/prep_build.sh
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image
        id: docker-build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # IMAGE_TAG: ${{ github.sha }}

        run: |
          echo "IMG_TAG = $IMG_TAG"
          cd build
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMG_TAG .
          # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMG_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMG_TAG" >> $GITHUB_OUTPUT
      
        