on:
  workflow_dispatch:



jobs:
  build-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Build, tag, and push image
        id: say-something

        run: |
          echo "This is staging build"
      
        