on:
  workflow_dispatch:



jobs:
  some-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build something
        id: build-something
        run: |
          echo "Building something"

  some-deploy:

    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy something
        id: say-something

        run: |
          echo "deploying something"
      
        