on:
  workflow_dispatch:



jobs:
  some-build:
    runs-on: ubuntu-latest
    steps:
      - name: build-something
        id: build-something
        run: |
          echo "Building something"
          echo "someval=This is some value" >> $GITHUB_OUTPUT

    outputs:
      some-value: ${{ steps.build-something.someval }}

  some-deploy:

    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy something
        id: say-something

        run: |
          echo "deploying something"
          echo "some value: ${{ needs.some-build.outputs.some-value }}"
    needs: some-build
      
        